<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Brisa.ico</ApplicationIcon>
    <RootNamespace>Brisa</RootNamespace>
    <StartupObject>Brisa.App</StartupObject>
    <Version>0.1.0-beta.5</Version>
    <Authors>insxnsive</Authors>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Product>Brisa</Product>
    <Description>Native Windows client for Brisa.</Description>
    <NoWarn>$(NoWarn);WPF0001;WFO0003</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="Velopack" Version="1.2.158" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>
</Project>
